from time import sleep
num = int(input('Digite um número para ver a sua tabuada:'))

print('{} x {} = {}'.format(num, 1, num*1))
sleep(1)
print('{} x {} = {}'.format(num, 2, num*2))
sleep(1)
print('{} x {} = {}'.format(num, 3, num*3))
sleep(1)
print('{} x {} = {}'.format(num, 4, num*4))
sleep(1)
print('{} x {} = {}'.format(num, 5, num*5))
sleep(1)
print('{} x {} = {}'.format(num, 6, num*6))
sleep(1)
print('{} x {} = {}'.format(num, 7, num*7))
sleep(1)
print('{} x {} = {}'.format(num, 8, num*8))
sleep(1)
print('{} x {} = {}'.format(num, 9, num*9))
sleep(1)
print('{} x {} = {}'.format(num, 10, num*10))